Metrics/MethodLength:
  Max: 50
  Exclude:
    - "test/**/*"
Metrics/AbcSize:
  Max: 30
  Exclude:
    - "test/**/*"
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
