require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

Metrics/MethodLength:
  Max: 50
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "test/**/*"

Performance:
  Exclude:
    - "test/**/*"

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  SafeAutoCorrect: true

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    default: "()"
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Include:
    - "app/**/*"
    - "config/**/*"
    - "examples/**/*"
    - "lib/**/*"
    - "test/**/*"
    - "Gemfile"

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Bundler/OrderedGems:
  Enabled: true
  SafeAutoCorrect: true
