Metrics/MethodLength:
  Max: 50
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "test/**/*"

Performance:
  Exclude:
    - "test/**/*"

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    default: "()"
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Include:
    - "app/**/*"
    - "config/**/*"
    - "examples/**/*"
    - "lib/**/*"
    - "test/**/*"
    - "Gemfile"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
